name: Build Mosquitto Plugin (x86-64, macOS)

on: [push, pull_request]

jobs:
  build-x86-64-macos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create builds directory
        run: mkdir -p builds

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Mosquitto
        run: |
          brew install mosquitto

      - name: Compile for x86-64
        run: |
          clang -arch x86_64 -fPIC -shared -o builds/x86-64.so mosquitto-js-auth.c \
          -I$(brew --prefix)/include -L$(brew --prefix)/lib -lmosquitto

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mosquitto-plugin-x86-64-macos
          path: builds/
