name: Build Mosquitto Plugin

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86-64, arm64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create builds directory
        run: mkdir -p builds




      - name: Set up QEMU for ARM emulation
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker environment for arm64
        if: matrix.arch == 'arm64'
        run: |
          docker run --rm --platform linux/arm64 -v $(pwd):/workspace -w /workspace arm64v8/ubuntu:20.04 /bin/bash -c "
          apt-get update && apt-get install -y build-essential libmosquitto-dev mosquitto-dev && \
          gcc -fPIC -shared -o builds/arm64.so mosquitto-js-auth.c -I/usr/include -L/usr/lib -lmosquitto
          "









      - name: Set up build environment on Ubuntu
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86-64'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libmosquitto-dev mosquitto-dev

      - name: Compile for x86-64 on Ubuntu
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86-64'
        run: |
          gcc -fPIC -shared -o builds/x86-64.so mosquitto-js-auth.c \
          -I/usr/include -L/usr/lib -lmosquitto









      - name: Set up Homebrew on macOS
        if: matrix.os == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Mosquitto on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install mosquitto

      - name: Compile for ${{ matrix.arch }} on macOS
        if: matrix.os == 'macos-latest'
        run: |
          HOMEBREW_PREFIX=$(brew --prefix)

          if [[ ${{ matrix.arch }} == 'arm64' ]]; then
            clang -arch arm64 -fPIC -shared -o builds/arm64.so mosquitto-js-auth.c \
            -I$HOMEBREW_PREFIX/include -L$HOMEBREW_PREFIX/lib -lmosquitto \
            -Wl,-undefined,dynamic_lookup

          elif [[ ${{ matrix.arch }} == 'x86-64' ]]; then
            clang -arch x86_64 -fPIC -shared -o builds/x86-64.so mosquitto-js-auth.c \
            -I$HOMEBREW_PREFIX/include -L$HOMEBREW_PREFIX/lib -lmosquitto

          fi







      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mosquitto-plugin-${{ matrix.os }}-${{ matrix.arch }}
          path: builds/
