name: Build Mosquitto Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        # arch: [x86-64, arm64]
        os: [macos-latest]
        arch: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mosquitto-dev
          if [[ ${{ matrix.arch }} == 'arm64' ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi

      - name: Set up Homebrew on macOS
        if: matrix.os == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Mosquitto on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install mosquitto

      - name: Compile for ${{ matrix.arch }} on ${{ matrix.os }}
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' && ${{ matrix.arch }} == 'arm64' ]]; then
            aarch64-linux-gnu-gcc -fPIC -shared -o builds/${{ matrix.arch }}.so mosquitto-js-auth.c \
            -I/usr/include -L/usr/lib -lmosquitto
          elif [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            gcc -fPIC -shared -o builds/${{ matrix.arch }}.so mosquitto-js-auth.c \
            -I/usr/include -L/usr/lib -lmosquitto
          else
            gcc -arch ${{ matrix.arch }} -fPIC -shared -o builds/${{ matrix.arch }}.so \
            mosquitto-js-auth.c -I/usr/local/include -L/usr/local/lib -lmosquitto
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mosquitto-plugin-${{ matrix.os }}-${{ matrix.arch }}
          path: builds/
